name: CloudFormation Lint and Deploy

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    name: Lint CloudFormation Templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Run cfn-lint on all templates
        run: |
          for file in templates/*.yaml; do
            echo "Linting $file"
            cfn-lint "$file"
          done

  deploy:
    name: Deploy CloudFormation Templates
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Deploy TGW stack (debug)
        run: |
          aws cloudformation deploy \
            --template-file templates/tgw-template.yaml \
            --stack-name tgw-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --role-arn ${{ secrets.AWS_CLOUDFORMATION_ROLE_ARN }} \
            --debug

      - name: Deploy VPC stack
        run: |
          aws cloudformation deploy \
            --template-file templates/vpc-template.yaml \
            --stack-name network-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --role-arn ${{ secrets.AWS_CLOUDFORMATION_ROLE_ARN }}

      - name: Deploy ALB/ECS stack
        run: |
          aws cloudformation deploy \
            --template-file templates/services-template.yaml \
            --stack-name services-misconfigured-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --role-arn ${{ secrets.AWS_CLOUDFORMATION_ROLE_ARN }}
